name: essentials_model
description: A new Flutter package project.
version: 0.0.1
homepage: none
publish_to: none


environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_modular: ^5.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  supabase_flutter: ^0.3.3
  # dependencies_module:   
  #   git:
  #     url: https://github.com/Store-preview-creator/dependencies_module.git
  #     ref: develop

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  logger: ^1.1.0
  

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: TTNorms_Bold
      fonts:
        - asset: assets/fonts/TTNormsPro_Bold.ttf
          
    - family: TTNorms_Medium
      fonts:
        - asset: assets/fonts/TTNormsPro_Medium.ttf
          
    - family: TTNorms_Regular
      fonts:
        - asset: assets/fonts/TTNormsPro_Regular.ttf
          
    - family: TTNormsPro_Light
      fonts:
        - asset: assets/fonts/TTNormsPro_Light.ttf
